#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    app,org=0,0
    upd_app=[]
    upd_org=[]

    for i in range(len(apples)):
        upd_app.append(apples[i]+ a)
    
    for j in range(len(oranges)):
        upd_org.append(oranges[j]+ b)

    for i in range(len(apples)):
        if upd_app[i] >=s and upd_app[i] <= t:
            app+=1

    for j in range(len(oranges)):
        if upd_org[j] >=s and upd_org[j] <= t:
            org+=1

    print(app)
    print(org)                         
if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
